- 모델을 학습시키기 위한 데이터는 파이토치의 텐서의 형태(torch.tensor)를 가지고 있어야 합니다


In [0]:
import torch.nn

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

![스크린샷 2020-03-18 오후 8 14 00](https://user-images.githubusercontent.com/44131043/76955198-14c7da80-6955-11ea-80e4-5c58c9987b8d.png)

- W = W - (알파* 기울기)

![스크린샷 2020-03-18 오후 8 15 37](https://user-images.githubusercontent.com/44131043/76955287-3d4fd480-6955-11ea-9184-1b8be87bbb19.png)


# pytorch _ linear reg

In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

#--------변수선언----------#
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(f'\n---x_train:--- \n {x_train}')
print(f'\n---x_train.shape:--- \n {x_train.shape}')

#------가중치와 편향의 초기화------#
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) # 1번쨰 size 
b = torch.zeros(1, requires_grad= True) # 
print(f'\n--------W:------- \n {W}')
print(W.shape) #1 

#----가설세우기------
hypothesis = x_train * W + b
print(f'\n-----hypothesis----:\n {hypothesis}')

#-----비용함수 선언-----
cost = torch.mean((hypothesis - y_train) **2)
print(f'\n cost: {cost}')

#---경사하강 구현-----
optimizer = optim.SGD([W,b], lr = 0.01) #학습 대상인 W와 b가 SGD의 입력이 됩니다.
    
    #gradient를 0으로 초기화 
optimizer.zero_grad()
    #비용 함수를 미분하여 gradient 계산
cost.backward()
    #W와 b를 업데이트
optimizer.step()






---x_train:--- 
 tensor([[1.],
        [2.],
        [3.]])

---x_train.shape:--- 
 torch.Size([3, 1])

--------W:------- 
 tensor([0.], requires_grad=True)
torch.Size([1])

-----hypothesis----:
 tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

 cost: 18.66666603088379


In [24]:
#전체 코드 

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1): #0~2000까지 

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() #gradient 0으로 초기화
    cost.backward() #비용 함수 미분해 gradient 계산
    optimizer.step() # w,b를 업데이트 

    # 100번마다 로그 출력
    #item으로 출력을 합니다 
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

# optimizer.zero_grad()가 필요한 이유

- 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있습니다. 예를 들어봅시다.
- 계속해서 미분값인 2가 누적되는 것을 볼 수 있습니다.   
그렇기 때문에 optimizer.zero_grad()를 통해 미분값을 __계속 0으로 초기화__ 시켜줘야 합니다


In [25]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  #cost
  z = 2*w  

#w로 미분
  z.backward() 
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


# autogard
- 사 하강법 코드를 보고있으면 requires_grad=True, backward() 등이 나옵니다.
- 는 파이토치에서 제공하고 있는 자동 미분(Autograd) 기능을 수행하고 있는 것입니다 

# autograd 실습


In [26]:
import torch

#이때 required_grad를 True로 
#이 텐서에 대한 기울기를 저장하겠다는 의미입니다. 
#이렇게 하면 w.grad에 w에 대한 미분값이 저장됩니다.

w = torch.tensor(2.0, requires_grad=True)

#수식정의
y= w**2
z= 2*y + 5

#해당 수식을 w에 대해 미분
#.backward()를 호출해 해당 수식의 w에대한 기울기 계싼
z.backward()

print('수식을 w로 미분한 값 : {}'.format(w.grad))


수식을 w로 미분한 값 : 8.0


# multivariable linear reg

In [32]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  

y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
    #print(x_train.shape) : [5,3]
    #print(W.shape): [3,1]

b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

#
nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    # x_train * W
    hypothesis = x_train.matmul(W) + b 

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() # optimizer 0세팅
    cost.backward() #gradient 계산
    optimizer.step() # 업데이트 

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371071
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo