In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

클래스(class) 형태의 모델은 nn.Module 을 상속받습니다.  
그리고 __init__()에서 모델의 구조와 동적을 정의하는 생성자를 정의합니다.  
이는 파이썬에서 객체가 갖는 속성값을 초기화하는 역할로,  
객체가 생성될 때 자동으호 호출됩니다.  
  
super() 함수를 부르면   
여기서 만든 클래스는 nn.Module 클래스의 속성들을 가지고 초기화 됩니다.     

foward() 함수는 모델이 학습데이터를 입력받아서   
forward 연산을 진행시키는 함수입니다.   
이 forward() 함수는 model 객체를 데이터와 함께 호출하면 자동으로 실행이됩니다.  
  
예를 들어 model이란 이름의 객체를 생성 후,   
model(입력 데이터)와 같은 형식으로 객체를 호출하면  
자동으로 forward 연산이 수행됩니다.

- H(x) 식에 입력 x로부터 예측된 y를 얻는 것을 forward 연산이라고 합니다.

In [0]:
#-------------------
model = nn.Linear(1,1)

#---위에 것을 class로 구현하면 아래와 같음---#

class LinearRegressionModel(nn.Module):

    def __init__(self):
        super().__init__()
        #단순 선형 회귀이므로 input_dim = 1, output_dim = 1
        self.linear = nn.Linear(1,1) 

    def forward(self, x):
        return self.linear(x)
        #nn.Linear(1,1)(x)


In [0]:
model = LinearRegressionModel()

In [0]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        #다중선형회귀이므로 input_dim = 3, out_dim = 1
        self.linear = nn.Linear(3,1) 

    def forward(self,x):
        return self.linear(x)
        #nn.Linear(1,1)(x)

In [0]:
model = MultivariateLinearRegressionModel()

# 2. 단순 선형 회귀 클래스로 구현하기

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [14]:
torch.manual_seed(1)

In [17]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train.shape, y_train.shape)

torch.Size([3, 1]) torch.Size([3, 1])


In [0]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)
        #nn.Linear(1,1)(x)

In [0]:
model = LinearRegressionModel()

In [22]:
print(type(model.parameters()))


optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

<class 'generator'>


In [26]:
nb_epochs = 2000

for epoch in range(nb_epochs + 1):

    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    # print(type(cost))
    # ---> torch.Tensor

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(epoch, nb_epochs, cost.item())

0 2000 3.632294465205632e-11
100 2000 2.8042753882906446e-11
200 2000 2.305947967295996e-11
300 2000 1.949729266925715e-11
400 2000 1.7678303265711293e-11
500 2000 1.593510566555434e-11
600 2000 1.3718211462621088e-11
700 2000 1.2979247017430584e-11
800 2000 1.2979247017430584e-11
900 2000 1.2979247017430584e-11
1000 2000 1.2278178473934531e-11
1100 2000 1.2278178473934531e-11
1200 2000 1.2278178473934531e-11
1300 2000 1.2278178473934531e-11
1400 2000 1.2278178473934531e-11
1500 2000 1.2278178473934531e-11
1600 2000 1.2278178473934531e-11
1700 2000 1.2278178473934531e-11
1800 2000 1.2278178473934531e-11
1900 2000 1.2278178473934531e-11
2000 2000 1.2278178473934531e-11


# 3. 다중선형회귀 

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [28]:
torch.manual_seed(1)


In [29]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

print(x_train.shape, y_train.shape)

torch.Size([5, 3]) torch.Size([5, 1])


In [0]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()

        #사이즈 잡아줘야함
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [0]:
model = MultivariateLinearRegressionModel()


In [0]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [41]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    
    #h(x)
    prediction = model(x_train)
    #model(x_train) = model.forward(x_train)과 동일하다 

    #cost
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    #미분해서 gradient 계산
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('{}\nEpoch {:4d}/{} Cost: {:.6f},  \n{}'.format(
          '-'*70,epoch, nb_epochs, cost.item(), list(model.parameters())
      ))


----------------------------------------------------------------------
Epoch    0/2000 Cost: 0.176020,  
[Parameter containing:
tensor([[0.9773, 0.4849, 0.5466]], requires_grad=True), Parameter containing:
tensor([0.2859], requires_grad=True)]
----------------------------------------------------------------------
Epoch  100/2000 Cost: 0.175930,  
[Parameter containing:
tensor([[0.9774, 0.4850, 0.5463]], requires_grad=True), Parameter containing:
tensor([0.2859], requires_grad=True)]
----------------------------------------------------------------------
Epoch  200/2000 Cost: 0.175851,  
[Parameter containing:
tensor([[0.9776, 0.4851, 0.5461]], requires_grad=True), Parameter containing:
tensor([0.2860], requires_grad=True)]
----------------------------------------------------------------------
Epoch  300/2000 Cost: 0.175764,  
[Parameter containing:
tensor([[0.9777, 0.4853, 0.5459]], requires_grad=True), Parameter containing:
tensor([0.2860], requires_grad=True)]
------------------------