#  nn.Module로 구현하는 선형 회귀

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [0]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [0]:
#하나의 입력 x에대하여 하나의 출력 y : -> 그래서 1,1
#model에는 가중치 w와 b가 저장되어 있음
#이 값은 model.parameters()로 가져올 수 있음
model = nn.Linear(1,1) 

출력되는데 첫번째 값이 W고, 두번째 값이 b에 해당됩니다.  
두 값 모두 현재는 랜덤 초기화가 되어져 있습니다.  
그리고 두 값 모두 학습의 대상이므로  
 requires_grad=True가 되어져

In [9]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [0]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [23]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch %100 ==0:
        print('Epoch {}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))
        

Epoch 0/2000 Cost: 0.000000
Epoch 100/2000 Cost: 0.000000
Epoch 200/2000 Cost: 0.000000
Epoch 300/2000 Cost: 0.000000
Epoch 400/2000 Cost: 0.000000
Epoch 500/2000 Cost: 0.000000
Epoch 600/2000 Cost: 0.000000
Epoch 700/2000 Cost: 0.000000
Epoch 800/2000 Cost: 0.000000
Epoch 900/2000 Cost: 0.000000
Epoch 1000/2000 Cost: 0.000000
Epoch 1100/2000 Cost: 0.000000
Epoch 1200/2000 Cost: 0.000000
Epoch 1300/2000 Cost: 0.000000
Epoch 1400/2000 Cost: 0.000000
Epoch 1500/2000 Cost: 0.000000
Epoch 1600/2000 Cost: 0.000000
Epoch 1700/2000 Cost: 0.000000
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [24]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print(pred_y)

tensor([[8.0000]], grad_fn=<AddmmBackward>)


In [25]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([8.7014e-06], requires_grad=True)]


# 다중선형회귀

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

#(5,3)
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
#(3,1)

#(5,1)
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [0]:
#model에는 3개의 가중치 w와 편향 b가 저장되어져 있습니다
model = nn.Linear(3,1)

In [31]:
#3개의 w와  1개의 b 
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.0803, -0.0707,  0.1601]], requires_grad=True), Parameter containing:
tensor([0.0285], requires_grad=True)]


In [0]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [33]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 24821.371094
Epoch  100/2000 Cost: 0.849148
Epoch  200/2000 Cost: 0.825597
Epoch  300/2000 Cost: 0.803225
Epoch  400/2000 Cost: 0.781968
Epoch  500/2000 Cost: 0.761779
Epoch  600/2000 Cost: 0.742587
Epoch  700/2000 Cost: 0.724357
Epoch  800/2000 Cost: 0.707025
Epoch  900/2000 Cost: 0.690548
Epoch 1000/2000 Cost: 0.674883
Epoch 1100/2000 Cost: 0.659985
Epoch 1200/2000 Cost: 0.645810
Epoch 1300/2000 Cost: 0.632342
Epoch 1400/2000 Cost: 0.619514
Epoch 1500/2000 Cost: 0.607307
Epoch 1600/2000 Cost: 0.595689
Epoch 1700/2000 Cost: 0.584616
Epoch 1800/2000 Cost: 0.574081
Epoch 1900/2000 Cost: 0.564045
Epoch 2000/2000 Cost: 0.554474


In [34]:
#3개의 w와 b의 값이 최적화 되었는지 확인 
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
#원래는 152임 실제 레이블 
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.6526]], grad_fn=<AddmmBackward>)


In [35]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7497, 0.4868, 0.7725]], requires_grad=True), Parameter containing:
tensor([0.0386], requires_grad=True)]
