In [1]:
import numpy as np

t = np.array([0., 2., 3., 4.,  5., 6.])
print(t)

[0. 2. 3. 4. 5. 6.]


In [2]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape) #(6,1)  == (6,)


Rank of t:  1
Shape of t:  (6,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근

print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.


t[0] t[1] t[-1] =  0.0 2.0 6.0
t[2:5] t[4:-1]  =  [3. 4. 5.] [5.]


In [5]:
#----------2d array--------------#
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [0]:
import torch

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim())
#torch.Size
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [11]:
#------2d pytorch-----#
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [20]:
print(t.shape)
print(t.size()[0])

torch.Size([4, 3])
4


In [22]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size(), '1차원 백터입니다') # ↑ 위의 경우의 크기 

tensor([ 2.,  5.,  8., 11.])
torch.Size([4]) 1차원 백터입니다


In [26]:
#--------broadcasting--------#
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]]) #1,2 
m2 = torch.FloatTensor([3]) # [3] -> [3, 3] //  1,1 
print(m1 + m2)

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) #1,2 -> 2, 2
m2 = torch.FloatTensor([[3], [4]]) #2,1 -> 2,2 
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


```python
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
```

In [27]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [32]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f'm1: \n {m1}')
print(f'm2: \n {m2}')

print('------------------------------')
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print('------------------------------')
print(m1 * m2) # 2 x 2 # element-wise 곱 
print(m1.mul(m2)) #matmul 

m1: 
 tensor([[1., 2.],
        [3., 4.]])
m2: 
 tensor([[1.],
        [2.]])
------------------------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
------------------------------
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


```python 
# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
[1]
[2]
==> [[1, 1],
     [2, 2]]
```

## mean

In [33]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(t.mean()) #4개 모두 더함

tensor(2.5000)


In [37]:
print(t.mean(dim = 0)) #행 제거 --> 열만남기겠다 -> (2,2) -> (1,2)
print(t.mean(dim = 1)) #열 제거 --> 행만남기겠따 -> (2,2) -> (2,1) 

tensor([2., 3.])
tensor([1.5000, 3.5000])


dim=0이라는 것은 첫번째 차원을 의미합니다.  
행렬에서 첫번째 차원은 '행'을 의미합니다.   
그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 됩니다.  
다시 말해 행렬에서 '열'만을 남기겠다는 의미가 됩니다

In [40]:
print(t.mean(dim = 0).shape) #행 제거 --> 열만남기겠다 -> (2,2) -> (1,2)
print(t.mean(dim = 1).shape) #열 제거 --> 행만남기겠따 -> (2,2) -> (2,1) 
#그러나 (2,1)은 결국 1차원이므로 (1,2)와 같이 나타나게 된다. 


torch.Size([2])
torch.Size([2])


In [41]:
#마지막 차원의 열으 제거하겠다 (열 차원 제거)
print(t.mean(dim=-1)) 

tensor([1.5000, 3.5000])


## 덧셈 

In [42]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [43]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and ArgMax
최대(Max)는 원소의 최대값을 리턴하고,  
아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴합니다.

In [50]:
t = torch.FloatTensor([[1, 9], [3, 4]])
print(t)

tensor([[1., 9.],
        [3., 4.]])


In [51]:
print(t.max()) # Returns one value: max

tensor(9.)


In [53]:
print(t)
print('------------------------')
print(t.max(dim=0)) # Returns two values: max and argmax
#max : 열에서 가장 큰 거 
#argmax : 열에서 가장 큰 값의 index 

tensor([[1., 9.],
        [3., 4.]])
------------------------
torch.return_types.max(
values=tensor([3., 9.]),
indices=tensor([1, 0]))


    훈련 데이터 하나의 크기를 256이라고 해봅시다. [3, 1, 2, 5, ...]   
    이런 숫자들의 나열이 256의 길이로 있다고 상상하면됩니다.  
    다시 말해 훈련 데이터 하나 = 벡터의 차원은 256입니다.  
    만약 이런 훈련 데이터의 개수가 3000개라고 한다면, 
    현재 전체 훈련 데이터의 크기는 3,000 × 256입니다.  (3000rows, 256cols)  
    행렬이니까 2D 텐서네요.   

    3,000개를 1개씩 꺼내서 처리하는 것도 가능하지만 
    컴퓨터는 훈련 데이터를 하나씩 처리하는 것보다   
    __보통 덩어리로 처리합니다__. 
    3,000개에서 64개씩 꺼내서 처리한다고 한다면   
    이 때 __batch size를 64__라고 합니다.
    __위 예에서는 64rows씩 처리를 한다__   

    그렇다면 컴퓨터가 한 번에 처리하는 2D 텐서의 크기는     (batch size × dim) = 64 × 256입니다.